MODULE = $(APPLICATION)

DIRS += $(RIOTCPU)/$(CPU) $(RIOTBOARD)/$(BOARD)
ifeq (1,$(RUST_BUILD))
DIRS += $(RIOTCPU)/rust/$(CPU)
endif
DIRS += $(RIOTBASE)/core $(RIOTBASE)/drivers $(RIOTBASE)/sys

include $(RIOTBASE)/Makefile.base
