MODULE = $(APPLICATION)

DIRS += $(RIOTCPU)/$(CPU) $(RIOTBOARD)/$(BOARD)
DIRS += $(RIOTBASE)/core $(RIOTBASE)/drivers $(RIOTBASE)/sys

ifeq (1,$(RUST_BUILD))
DIRS += $(RIOTRUST)
endif

include $(RIOTBASE)/Makefile.base
